### ISSUE TITLE
ExcelToCSV-Export

### ISSUE THREAD

**Issue by opensource21** [rdmueller/docToolchain#33]
I wondering if you have a task which exports every sheet of excelfiles to csv, so that they can included into asciidoc. 
Can you provide an idea how to add a gradle task to the project? Must there a task for maven too?

**Comment by rdmueller** [comment]
I was planning to create a task which turns an excel sheet into an asciidoc table.
Regarding the csv, I often just use a csv file which is automatically opened by windows with excel.
But you are right, an ExcelToCSV Task would make sense.

I see two approaches here: 
- a vbs-script to do a save-as-csv
- save the excel as xml and use a groovy script
- (use apache POI, but I don't like this aproach)

the exportChangeLog task is an example for a groovy script.
the exportPPT task s an example for a vbs script.

If you like, you could also introduce kotlin :-)

...and regarding maven: I've given up on maven by now. It is just too complex...

**Comment by opensource21** [comment]
Thanks for the hints I will see if I can manage it as Gradle newbie. I think the idea to export directly to asciidoc is not so smart because you have than no influence on the configuration of the table.

**Comment by rdmueller** [comment]
great!
regarding the configuration of the table - I dream of a script which converts the excel cell formatting (bold, alignment) into AsciiDoc cell formattings... 
AsciiDoc is capable of so many features regarding the table cells, but it is so hard to remember everything...
