### ISSUE TITLE
Confluence: Code block with type [BUG]

### ISSUE THREAD

**Issue by MoePad** [rdmueller/docToolchain#44]
Hi Ralf,

first: thanks for your amazing tool! I heard of this in a seminar of Dr. Starke and Dr. Hrushka and immediatly fall in love with it!

I tackeled down a very weird bug:

### Precondition
Inside the arc42 documentation a code block declared like this:
```
[source,java]
----
public class Test {
}
----
```

### Expectations
A nice rendered block of Java code.

### Actual result
Error during the publishToConfluence task:
```
something went wrong - got an http response code 400:
[statusCode:400, data:[authorized:false, valid:true, errors:[], successful:false], message:Error parsing xhtml: String ']]>' not allowed in textual content, except as the end marker of CDATA section
```

### Workaround
Remove `java` from the declaration. The declaration would look like this now:
```
[source]
----
public class Test {
}
----
```
Then, everything works fine.

--

If you can show me where to fix this, I can try. Or if you need additional information or anything, let me know. Thanks again for this awesome tool!

**Comment by rdmueller** [comment]
Great to hear that you like docToolchain! I hope you also follow me on twitter :-) @docToolchain

Regarding the Bug:

Confluence uses xhtml as internal storage format. The script uses the asciidoctor html output and publishes it to confluence.

It seems that the html output is not always valid xhtml. Often there are closing tags (like for <br>) missing.
This seems to be also the problem in this case. The script already contains some fixes for these situations, but I guess we have to add more :-)

https://github.com/rdmueller/docToolchain/blob/master/scripts/asciidoc2confluence.groovy#L203

I'll see what I can fix over the weekend...

**Comment by MoePad** [comment]
Thanks for the hint. I fixed it and added correct language support for confluence. Please see my pull request.

**Comment by rdmueller** [comment]
Seems to work quite well...

Welcome to the group of docToolchain committers!

**Comment by MoePad** [comment]
Thanks for the feedback. I'm glad I could help!
