### ISSUE TITLE
internal cross-references do not work in Confluence export

### ISSUE THREAD

**Issue by bodewig** [rdmueller/docToolchain#49]
`asciidoctor` generated HTML uses `id` attributes as anchors for links. When the pages get published to Confluence the ids get partly stripped and partly rewritten by Confluence so all anchors are lost. In addition the links themselves need to get rewritten as the content is now spread across multiple pages.

The code in https://github.com/bodewig/docToolchain/tree/internal_links gets pretty close but is not ready for a PR, yet.

What it does:

* add a Confluence anchor macro for every `id` attribute.
* keep track of the pages anchors appear on, also record anchors corresponding to the elements that now become page titles and no longer appear inside the DOM at all.
* replace all links whose `href`s start with `#` with Confluence link macros

I still need to take `confluencePagePrefix` into account, but this is trivial.

The Confluence link macro expects the link text to be inside a `CDATA`-section. I.e.

```
<ac:link ac:anchor="foo-anchor"><ri:page ri:content-title="1. Bar" /><ac:plain-text-link-body>Baz</ac:plain-text-link-body></ac:link>
```

renders a link with text "1. Bar#foo-anchor" while

```
<ac:link ac:anchor="foo-anchor"><ri:page ri:content-title="1. Bar" /><ac:plain-text-link-body><![CDATA[Baz]]></ac:plain-text-link-body></ac:link>
```

renders a link with text "Baz". We clearly want the latter.

Unfortunately I haven't found a way to tell JSoup I want a CDATA section and when I add it manually JSoup strips it (which is perfectly fine from an XML point of view). So I came up with the ugly hack of introducing my own `cdata-placeholder` element and replacing it when the DOM tree is rendered as a string. This feels wrong, better ideas are welcome.

`CDATA` also means you can't have HTML markup inside of your link text, it currently gets rendered escaped, i.e. "&lt;code>Foo&lt;/code>" rather than "`Foo`" if you've used something like ``<<foo-anchor,`Foo`>>`` for your link. I plan to replace the `innerHTML` of the link I replace with its `text`, which would mean we lose styling but don't get to see literal content.

The branch currently also contains code I've later removed (rewriting `a` tags with `name` attributes as anchor macros as well, and not considering `id`s that start with a `_`). Should I rebase the branch to remove this intermezzo or even squash it to a single commit before I open a PR?

Also, is there a good place to add documentation at the same time? I think the effect of lost styling is something that may come as a surprise and should be documented somewhere.

**Comment by bodewig** [comment]
see #50

**Comment by rdmueller** [comment]
> Should I rebase the branch to remove this intermezzo or even squash it to a single commit before I open a PR?

No extra efforts here - the original history with all it flaws is ok.

> Also, is there a good place to add documentation at the same time?

I currently maintain the manual here:
https://github.com/rdmueller/docToolchain/blob/master/src/docs/manual.adoc

This then gets rendered to https://rdmueller.github.io/docToolchain/

As you can see, I haven't documented the complexer tasks yet, but want to do so soon.
Maybe we leave this issue open as reminder and as soon as I document the publishToConfluence part, I use your input to add the details...

**Comment by bodewig** [comment]
Ah, I had seen the manual but wasn't sure whether there was anything else.

Sounds good, so I'll close this issue now.

Thanks.
