### ISSUE TITLE
"headline promotion" in Confluence export is inconsistent

### ISSUE THREAD

**Issue by bodewig** [rdmueller/docToolchain#51]
Right now when `confluenceCreateSubpages` is `true` all headlines get "promoted" to higher levels (i.e. `h4` becomes `h1` and so on). Shouldn't the same also be done for the pages created from `h2` as well, just with one level less of promoting - i.e. `h3` becomes `h1` and so on?

I'll be happy to take a stab myself, Before I do so I just want to make sure the difference is not an intentional one.

**Comment by rdmueller** [comment]
yes, I guess you are absolutely right. The difference is not intentional
