### ISSUE TITLE
Confluence "Children Macro" Sort Order

### ISSUE THREAD

**Issue by bodewig** [rdmueller/docToolchain#54]
When exporting to Confluence the "children" macro is added at the bottom of each page. The script doesn't specify any order explicitly and it seems "sort by title" is the default choice.

When using section numbers this starts to look weird as soon as you get to chapter 10 :-)

The other sort options are "creation" and "modification".

Given the way the script works, pages should get created in the same order they appear inside the document that is being exported. So maybe explicitly sorting by "creation" would be better?

The alternatives are "leave it as it is" and "make it configurable".

**Comment by rdmueller** [comment]
so, let's give "creation" a try...
 or start to number like 01, 02, 03 :-)
