### ISSUE TITLE
problem with script plugins

### ISSUE THREAD

**Issue by rdmueller** [rdmueller/docToolchain#64]
the `build.gradle` file grew by now to an enourmous size.

today I tried to use script plugins in order to create several modules. This seems to work great for most tasks, but it doesn't work for the `htmlSanityCheck`

**Comment by rdmueller** [comment]
see https://github.com/rdmueller/docToolchain/blob/deckjs/scripts/htmlSanityCheck.gradle

**Comment by bodewig** [comment]
what does one need to do to see the problem the comment talks about?

**Comment by rdmueller** [comment]
Just include the externalized code by using an 'apply from' statement in the main build file. 
A 'gradle tasks' should then be enough to invoke the error

**Comment by bodewig** [comment]
I think this is what you need to do:

* in `htmlSanityCheck.gradle` line 13 add quotes around `org.aim42.htmlSanityCheck`
* in `build.gradle` move the definition of `checkingResultsPath` to the `ext` closure

after these changes `./gradlew tasks` works for me. I haven't checked anything more than that, though.

BTW, `gradlew` should probably be executable.

**Comment by rdmueller** [comment]
cool. I thought I already tried everything. It works! thanx!

regarding `gradlew`: true, but hard to do from windows. will open another issue...
