### ISSUE TITLE
Separate tool from data

### ISSUE THREAD

**Issue by jakubjab** [rdmueller/docToolchain#71]
I would like to have docToolchain separately as a tool, which can be imported into our build system and used for multiple software systems without changing.

Currently src directory is embedded in the tool, which makes it hard to maintain - we cannot just pull new version of the tool from GitHub and use it without moditications.

It's also licensing problem, because the license for the tool may be different than the license for the documentation itself.

My proposal is to pass all the parameters to gradlew in the command line (e.g. with -P option), so that we could run e.g. gradlew -PsourceDir=/someProjectA, etc.

I started to work on that, but before continuing I'd like to agree with authors.

**Comment by rdmueller** [comment]
sounds like a plan!
I also noticed that within the repo, the tool, manual, arc42 template and examples are mixed. In addition, I would like to add some automated tests.

So a better structure would be a great idea - can you suggest one?

And please take a look at the deck.js branch. There I have already "modularized" the build file. It now consists mainly of references to script plugins. Maybe that's a start...

@opensource21 , @bodewig : what are your thoughts?

**Comment by bodewig** [comment]
I'm all for the separation. For our local projects I'm maintaining a local fork of the tooling (and only the tooling) as this is all we need.

**Comment by rdmueller** [comment]
So, I wander what will be the best way to make this modular.
We have three big modules:
- docToolchain itself with or without arc42
- the eat-your-own-dogfood manual with examples
- hopefully some more tests in the future

1) I personally think it would be cool to have something like http://start.spring.io/ to create your own flavor.

2) docToolchain could also be divided into several Gradle plugins and you manually select your tools you need.

3) third option is to break it all up into three repositories.

What do you think? Which option do you prefer? Are there even additional options?

@jakubjab : about the licensing: do you already see a licensing problem?

**Comment by jakubjab** [comment]
I would vote for splitting it into separate repositories:
1) docToolchain without any template
2) manual and examples
3) arc42 template

If you want just to use the tool, download 1) and include in your build system.
If you want to use and develop the tool, download 1) and 2).
If you want arc42 template, download 3), or use any other template available. You could consider if it's not better just to refer to official arc42 template instead of maintaining your copy, see https://github.com/arc42/arc42-template.

As for licensing, current docToolchain includes arc42, which is also licensed separately on Creative-Commons Sharealike 4.0., see http://faq.arc42.org/questions/A-2/. That's a little unclear, but probably not a big problem.

**Comment by rdmueller** [comment]
what if we add an "init" task to docToolchain which fetches the arc42 template and helps with the configuration?

**Comment by jakubjab** [comment]
For me the most important thing is that docToolchain takes input/output directories, Confluence configuration, etc. from the command line (or from files whose paths are given on the command line). I plan to work on that in my fork (unless @bodewig has the solution already). The template and manual can stay there for now, I can just remove them after downloading.

**Comment by bodewig** [comment]
I'd also vote for giving docToolchain a repo of its own.

Unfortunately I cannot provide a solution as we are really just using a subset of doTolchain's abilities and thus the fork only contains what we need.

@rdmueller I like the idea of the "init" task but would ensure it also carries arc42 in its name (init-ar42?) as docToolchain is useful beyond arc42.

**Comment by rdmueller** [comment]
@bodewig regarding the init task - I guess it will not only copy the arc42 template but also help with the `publishToConfluence`and other configurations...

@jakubjab afaik, configs from the `gradle.properties` can be overwritten by the command line. So I guess some settings are already prepared for that approach and others have to be unified...

**Comment by rdmueller** [comment]
@jakubjab I've opened another issue for the command line properties: https://github.com/rdmueller/docToolchain/issues/74

**Comment by jakubjab** [comment]
If you don't mind, I would like to close this issue now, as my goal with separation has been achieved.

**Comment by rdmueller** [comment]
yes, thanx. The tests have already proven how flexible your new approach is!
