### ISSUE TITLE
Endless Excel-File

### ISSUE THREAD

**Issue by rdmueller** [rdmueller/docToolchain#84]
It seems that there are cases where Apache POI thinks that the Excel file is "endless".
In this case, lots of empty rows are generated.

**Comment by bodewig** [comment]
Before diving into it, have you re-checked with a more recent version of POI? 3.9 is pretty old.

**Comment by rdmueller** [comment]
it seems that it depends somehow on the excel file. Maybe the version of excel, maybe how someone modified it (select all + fomat cell ?).
If this happens, the script will export a huge amount of empty rows.
I will implement something that the export stops after 3 empty rows. That should be OK, shouldn't it?

**Comment by bodewig** [comment]
I'm not familiar with the excel export so wouldn't know whether a legitimate export could ever contain more than three empty rows, maybe make that ten? You probably should upgrade the dependency while you are at it, anyway.
